import Link from 'next/link'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="mb-2 flex min-h-screen flex-col bg-zinc-400">
        <main className="">
          <nav className="flex flex-shrink-0 items-center justify-between border-b-[1px] border-zinc-900 p-4">
            <div className="flex items-center">
              <h1 className="ml-2 text-2xl font-bold">AuthApp</h1>
            </div>
            <div className="flex items-center gap-2">
              <Link href="/">Home</Link>
              <Link href="/about">About</Link>
              <Link href="/dashboard">Dashboard</Link>
            </div>
          </nav>
          <div className="ml-2 mt-2">{children}</div>
        </main>
      </body>
    </html>
  )
}
